export interface TableData {
    id: number;
    direction: string;
    seats: number;
    candidates: number;
};

export const data: TableData[] = [
    { id: 1, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 2, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 3, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 4, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 5, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 6, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 7, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 8, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 9, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 10, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 11, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 12, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 13, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 14, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 15, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 16, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 17, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 18, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 19, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 20, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 21, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 22, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 23, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 24, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 25, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 26, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 27, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 28, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 29, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 30, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 31, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 32, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 33, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 34, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 35, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 36, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 37, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 38, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 39, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 40, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 41, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 42, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 43, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 44, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 45, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 46, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 47, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 48, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 49, direction: 'Python (AО)', seats: 75, candidates: 45 },
    { id: 50, direction: 'Python (AО)', seats: 75, candidates: 45 }
]